### ISSUE TITLE
mmwave-radio-energy-model-enb.cc attribute values

### ISSUE THREAD

**Issue by danielrluna** [arghasen10/mmwave-energy#2]
Hello,

Firstly, thank you very much for this energy module, it's been very helpful for my research. 

I have one question, though.  I was wondering where the attribute values from mmwave-radio-energy-model-enb.cc come from. Is it from a paper or 3ppp standard? Could you kindly provide where it came from.

I know that the atribute values from mmwave-energy.cc are available in the paper "An ns3-based Energy Module of 5G NR User Equipments for Millimeter Wave Networks", however I could not find the ones for the enb energy mode.

Thank you in advance.

**Comment by arghasen10** [comment]
Hi, @danielrluna please have a look at this [paper](https://ieeexplore.ieee.org/document/7145603). The power specifications for the base station energy module are taken from this paper.

**Comment by danielrluna** [comment]
Thank you @arghasen10
